/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three/examples/jsm/loaders/GLTFLoader";

type GLTFResult = GLTF & {
  nodes: {
    Cube: THREE.Mesh;
    Cube001: THREE.Mesh;
    desk: THREE.Mesh;
    Cube005: THREE.Mesh;
    Plane: THREE.Mesh;
    Cylinder: THREE.Mesh;
    Cube006: THREE.Mesh;
    Cube007: THREE.Mesh;
    Cylinder001: THREE.Mesh;
    Cube009: THREE.Mesh;
    Plane001: THREE.Mesh;
    Cube003: THREE.Mesh;
    Cube016: THREE.Mesh;
    Cube018: THREE.Mesh;
    Cube010: THREE.Mesh;
    Cube056_1: THREE.Mesh;
    Cube056_2: THREE.Mesh;
    Plane002: THREE.Mesh;
    Cube011: THREE.Mesh;
    Cube013: THREE.Mesh;
    Cube012: THREE.Mesh;
    Cube014: THREE.Mesh;
    Cube017: THREE.Mesh;
    Cube019: THREE.Mesh;
    Cube020: THREE.Mesh;
    Cube021: THREE.Mesh;
    Cube022: THREE.Mesh;
    Cube004: THREE.Mesh;
    Cube008: THREE.Mesh;
    Cube023: THREE.Mesh;
    Cylinder002: THREE.Mesh;
    Cube002: THREE.Mesh;
    Cube024: THREE.Mesh;
    Cube025: THREE.Mesh;
    Torus001: THREE.Mesh;
    Torus002: THREE.Mesh;
    Torus003: THREE.Mesh;
    Circle: THREE.Mesh;
    Cube029_1: THREE.Mesh;
    Cube029_2: THREE.Mesh;
    Cube029_3: THREE.Mesh;
    Cube029_4: THREE.Mesh;
    Cube029_5: THREE.Mesh;
    Cube029_6: THREE.Mesh;
    Cube033: THREE.Mesh;
    Cylinder006_1: THREE.Mesh;
    Cylinder006_2: THREE.Mesh;
    Cylinder006_3: THREE.Mesh;
    Cube029: THREE.Mesh;
    Cube030: THREE.Mesh;
    Cube031: THREE.Mesh;
    Cube032: THREE.Mesh;
    Cube034: THREE.Mesh;
    Cube035: THREE.Mesh;
    Cube036: THREE.Mesh;
    Cube037: THREE.Mesh;
    Cube038: THREE.Mesh;
    Cube039: THREE.Mesh;
    Cube040: THREE.Mesh;
    Cube041: THREE.Mesh;
    Cube016_1: THREE.Mesh;
    Cube016_2: THREE.Mesh;
    Cube020_1: THREE.Mesh;
    Cube020_2: THREE.Mesh;
    Cube021_1: THREE.Mesh;
    Cube021_2: THREE.Mesh;
    Cube023_1: THREE.Mesh;
    Cube023_2: THREE.Mesh;
    Cube024_1: THREE.Mesh;
    Cube024_2: THREE.Mesh;
    Cube026_1: THREE.Mesh;
    Cube026_2: THREE.Mesh;
    Cube027_1: THREE.Mesh;
    Cube027_2: THREE.Mesh;
    Plane004: THREE.Mesh;
    Cube050: THREE.Mesh;
    Cube051: THREE.Mesh;
    Cube052: THREE.Mesh;
    Cube055: THREE.Mesh;
    Cube056: THREE.Mesh;
    Cube053: THREE.Mesh;
    Cube054: THREE.Mesh;
    Cube057: THREE.Mesh;
    Cube058: THREE.Mesh;
    Cube059: THREE.Mesh;
    Cube060: THREE.Mesh;
    Cube061: THREE.Mesh;
    Cube062: THREE.Mesh;
    Cube063: THREE.Mesh;
    Cube064: THREE.Mesh;
    Cube065: THREE.Mesh;
    Cube066: THREE.Mesh;
    Cylinder004: THREE.Mesh;
    Cylinder005: THREE.Mesh;
    Cylinder006: THREE.Mesh;
    Cube067: THREE.Mesh;
    Cube068: THREE.Mesh;
    Cylinder007: THREE.Mesh;
    Cube069: THREE.Mesh;
    Cube070: THREE.Mesh;
    Circle001: THREE.Mesh;
    Cylinder008: THREE.Mesh;
    Cube072: THREE.Mesh;
    Cylinder010: THREE.Mesh;
    Cylinder012: THREE.Mesh;
    Torus004_1: THREE.Mesh;
    Torus004_2: THREE.Mesh;
    Torus004_3: THREE.Mesh;
    Cube074_1: THREE.Mesh;
    Cube074_2: THREE.Mesh;
    Cube074_3: THREE.Mesh;
    Cube075_1: THREE.Mesh;
    Cube075_2: THREE.Mesh;
    Cube075: THREE.Mesh;
    Cylinder009: THREE.Mesh;
    Cube076: THREE.Mesh;
    Cube077: THREE.Mesh;
    Cube078: THREE.Mesh;
    Cube079: THREE.Mesh;
    Cube080: THREE.Mesh;
    Cube081: THREE.Mesh;
    Cube082: THREE.Mesh;
    Cube083: THREE.Mesh;
    Cube084: THREE.Mesh;
    Cube085: THREE.Mesh;
    Cube086: THREE.Mesh;
    Cube087: THREE.Mesh;
    Cube088: THREE.Mesh;
    Cube089: THREE.Mesh;
    Cube090: THREE.Mesh;
    Cube094: THREE.Mesh;
    Cube095: THREE.Mesh;
    Cube096: THREE.Mesh;
    Cube091: THREE.Mesh;
    Cube092: THREE.Mesh;
    Cube093: THREE.Mesh;
    Cube097: THREE.Mesh;
    Cube098: THREE.Mesh;
    Cube099: THREE.Mesh;
    Plane003: THREE.Mesh;
    Plane005: THREE.Mesh;
    Plane006: THREE.Mesh;
    Plane007: THREE.Mesh;
    Plane008: THREE.Mesh;
    Plane009: THREE.Mesh;
    Plane010: THREE.Mesh;
    Plane011: THREE.Mesh;
    Plane012: THREE.Mesh;
    Plane013: THREE.Mesh;
    Plane014: THREE.Mesh;
    Plane015: THREE.Mesh;
    Plane016: THREE.Mesh;
    Plane017: THREE.Mesh;
    Plane018: THREE.Mesh;
    Plane019: THREE.Mesh;
    Plane020: THREE.Mesh;
    Plane021: THREE.Mesh;
    Plane022: THREE.Mesh;
    Plane023: THREE.Mesh;
    Plane024: THREE.Mesh;
    Plane025: THREE.Mesh;
    Plane026: THREE.Mesh;
    Plane027: THREE.Mesh;
    Plane028: THREE.Mesh;
    Plane029: THREE.Mesh;
    Cylinder011: THREE.Mesh;
    Cylinder020_1: THREE.Mesh;
    Cylinder020_2: THREE.Mesh;
    Cylinder014: THREE.Mesh;
    Cylinder015: THREE.Mesh;
    Cylinder016: THREE.Mesh;
    Cube110: THREE.Mesh;
    Cube110_1: THREE.Mesh;
    Cube110_2: THREE.Mesh;
    Cylinder017: THREE.Mesh;
    Cylinder018: THREE.Mesh;
    Cube111: THREE.Mesh;
    Cube111_1: THREE.Mesh;
    Cylinder026_1: THREE.Mesh;
    Cylinder026_2: THREE.Mesh;
    Cylinder027_1: THREE.Mesh;
    Cylinder027_2: THREE.Mesh;
    Cylinder021: THREE.Mesh;
    Cylinder022: THREE.Mesh;
    Circle019: THREE.Mesh;
    Cube102: THREE.Mesh;
    Cylinder023: THREE.Mesh;
    Cylinder024: THREE.Mesh;
    Cylinder025: THREE.Mesh;
    Cylinder026: THREE.Mesh;
    Plane030: THREE.Mesh;
    Plane031: THREE.Mesh;
    Plane032: THREE.Mesh;
    Plane033: THREE.Mesh;
    Plane034: THREE.Mesh;
    Plane035: THREE.Mesh;
    Circle002: THREE.Mesh;
    Cylinder027: THREE.Mesh;
    Sphere: THREE.Mesh;
    Cylinder028: THREE.Mesh;
    Torus005: THREE.Mesh;
    Cylinder030: THREE.Mesh;
    Cylinder031: THREE.Mesh;
    Cylinder032: THREE.Mesh;
    Cube114: THREE.Mesh;
    Cube114_1: THREE.Mesh;
    Icosphere002: THREE.Mesh;
    Icosphere002_1: THREE.Mesh;
    Cube071: THREE.Mesh;
    Cube027: THREE.Mesh;
  };
  materials: {
    doorMaterial: THREE.MeshStandardMaterial;
    wallMaterial: THREE.MeshStandardMaterial;
    deskMaterial: THREE.MeshStandardMaterial;
    monStandMaterial: THREE.MeshStandardMaterial;
    computerMaterial: THREE.MeshStandardMaterial;
    deskBlack: THREE.MeshStandardMaterial;
    mousePadMaterial: THREE.MeshStandardMaterial;
    floorMaterial: THREE.MeshStandardMaterial;
    psMaterial: THREE.MeshStandardMaterial;
    psIntMaterial: THREE.MeshStandardMaterial;
    chairMaterials: THREE.MeshStandardMaterial;
    tubesMaterial: THREE.MeshStandardMaterial;
    ["wallMaterial.001"]: THREE.MeshStandardMaterial;
    whiteMaterial: THREE.MeshStandardMaterial;
    mattMaterial: THREE.MeshStandardMaterial;
    boltsMaterial: THREE.MeshStandardMaterial;
    ropeMaterial: THREE.MeshStandardMaterial;
    redCubeMaterial: THREE.MeshStandardMaterial;
    whiteCubeMaterial: THREE.MeshStandardMaterial;
    blueCubeMaterial: THREE.MeshStandardMaterial;
    greenCubeMaterial: THREE.MeshStandardMaterial;
    yellCubeMaterial: THREE.MeshStandardMaterial;
    chalkBagMaterial: THREE.MeshStandardMaterial;
    blueBagMaterial: THREE.MeshStandardMaterial;
    ["Material.005"]: THREE.MeshStandardMaterial;
    bookMaterial: THREE.MeshStandardMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
    darkwoodMaterial: THREE.MeshStandardMaterial;
    meshMaterial: THREE.MeshStandardMaterial;
    ["Material.007"]: THREE.MeshStandardMaterial;
    blackBallMaterial: THREE.MeshStandardMaterial;
    ["Material.008"]: THREE.MeshStandardMaterial;
    cactusMaterial: THREE.MeshStandardMaterial;
    dirtMaterial: THREE.MeshStandardMaterial;
  };
};

export default function Model(
  props: JSX.IntrinsicElements["group"]
): JSX.Element {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF("/myroom.glb") as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials.doorMaterial}
        position={[-1.62, 7.27, 0.21]}
        rotation={[0, -0.25, 0]}
      />
      <mesh
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[-2.31, 7.85, 6.64]}
        rotation={[0, -0.25, 1.57]}
      />
      <mesh
        geometry={nodes.desk.geometry}
        material={nodes.desk.material}
        position={[-0.65, 1.69, 0.97]}
        rotation={[0, -0.25, 1.57]}
      />
      <mesh
        geometry={nodes.Cube005.geometry}
        material={nodes.Cube005.material}
        position={[0.53, 3.91, 3.79]}
        rotation={[-Math.PI, 0.25, -Math.PI]}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[-0.34, 4.78, 3.55]}
        rotation={[-Math.PI, 0.25, -1.57]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[-0.18, 5.65, 3.47]}
        rotation={[-1.57, 0, 2.89]}
      />
      <mesh
        geometry={nodes.Cube006.geometry}
        material={nodes.Cube006.material}
        position={[-0.03, 5.09, 3.62]}
        rotation={[3.13, 0.25, 1.49]}
      />
      <mesh
        geometry={nodes.Cube007.geometry}
        material={nodes.Cube007.material}
        position={[1.66, 3.95, 4.02]}
        rotation={[Math.PI, 0.25, -3.01]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
        position={[0.84, 4, 4.41]}
        rotation={[-1.57, 0, 2.89]}
      />
      <mesh
        geometry={nodes.Cube009.geometry}
        material={nodes.Cube009.material}
        position={[2.45, 3.41, 1.82]}
        rotation={[-Math.PI, 0.25, -1.57]}
      />
      <mesh
        geometry={nodes.Plane001.geometry}
        material={nodes.Plane001.material}
        position={[1.64, 3.96, 2.16]}
        rotation={[-Math.PI, 0.25, -Math.PI]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={nodes.Cube003.material}
        position={[-1.83, 7.88, 1.06]}
        rotation={[0, -0.25, 0]}
      />
      <mesh
        geometry={nodes.Cube016.geometry}
        material={nodes.Cube016.material}
        position={[-3.66, 7.88, 8.32]}
        rotation={[0, -0.25, 0]}
      />
      <mesh
        geometry={nodes.Cube018.geometry}
        material={nodes.Cube018.material}
        position={[-3.92, 7.88, 9.36]}
        rotation={[0, -0.25, 0]}
      />
      <mesh
        geometry={nodes.Cube010.geometry}
        material={nodes.Cube010.material}
        position={[1.71, 3.75, 2.08]}
        rotation={[-Math.PI, 0.25, -Math.PI]}
      />
      <group
        position={[0.31, 4.35, 0.2]}
        rotation={[-Math.PI, -1.32, -Math.PI]}
      >
        <mesh
          geometry={nodes.Cube056_1.geometry}
          material={materials.psMaterial}
        />
        <mesh
          geometry={nodes.Cube056_2.geometry}
          material={materials.psIntMaterial}
        />
      </group>
      <mesh
        geometry={nodes.Plane002.geometry}
        material={nodes.Plane002.material}
        position={[-6.86, 0.33, 5.11]}
        rotation={[0, -0.25, 0]}
      />
      <mesh
        geometry={nodes.Cube011.geometry}
        material={nodes.Cube011.material}
        position={[2.43, 1.29, 4.15]}
        rotation={[-Math.PI, 0.25, -Math.PI]}
      />
      <mesh
        geometry={nodes.Cube013.geometry}
        material={nodes.Cube013.material}
        position={[3.3, 0.22, 3.36]}
        rotation={[-Math.PI, 0.25, -Math.PI]}
      />
      <mesh
        geometry={nodes.Cube012.geometry}
        material={nodes.Cube012.material}
        position={[1.98, 0.22, 3.03]}
        rotation={[-Math.PI, 0.25, -Math.PI]}
      />
      <mesh
        geometry={nodes.Cube014.geometry}
        material={nodes.Cube014.material}
        position={[1.49, 0.22, 4.97]}
        rotation={[0, -0.25, 0]}
      />
      <mesh
        geometry={nodes.Cube017.geometry}
        material={nodes.Cube017.material}
        position={[2.81, 0.22, 5.3]}
        rotation={[0, -0.25, 0]}
      />
      <mesh
        geometry={nodes.Cube019.geometry}
        material={nodes.Cube019.material}
        position={[2.27, 3.21, 4.11]}
        rotation={[-Math.PI, 0.25, -1.48]}
      />
      <mesh
        geometry={nodes.Cube020.geometry}
        material={nodes.Cube020.material}
        position={[2.43, 3.97, 4.15]}
        rotation={[-Math.PI, 0.25, -1.48]}
      />
      <mesh
        geometry={nodes.Cube021.geometry}
        material={nodes.Cube021.material}
        position={[2.59, 4.74, 4.19]}
        rotation={[-Math.PI, 0.25, -1.48]}
      />
      <mesh
        geometry={nodes.Cube022.geometry}
        material={nodes.Cube022.material}
        position={[2.75, 5.52, 4.23]}
        rotation={[-Math.PI, 0.25, -1.48]}
      />
      <mesh
        geometry={nodes.Cube004.geometry}
        material={nodes.Cube004.material}
        position={[17.88, 7.85, -11.8]}
        rotation={[Math.PI, -1.33, -1.57]}
      />
      <mesh
        geometry={nodes.Cube008.geometry}
        material={nodes.Cube008.material}
        position={[2.61, 5.88, -15.63]}
        rotation={[-1.57, 0, -0.25]}
      />
      <mesh
        geometry={nodes.Cube023.geometry}
        material={nodes.Cube023.material}
        position={[2.33, 7.85, -15.63]}
        rotation={[Math.PI, -1.33, -1.57]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={nodes.Cylinder002.material}
        position={[1.11, 0.62, -6.25]}
        rotation={[0, -0.25, 0]}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={nodes.Cube002.material}
        position={[-0.14, 9.09, -5.64]}
        rotation={[0, -0.25, 0]}
      />
      <mesh
        geometry={nodes.Cube024.geometry}
        material={nodes.Cube024.material}
        position={[-0.14, 6.17, -5.64]}
        rotation={[0, -0.25, 0]}
      />
      <mesh
        geometry={nodes.Cube025.geometry}
        material={nodes.Cube025.material}
        position={[-1.75, 12.63, -7.79]}
        rotation={[0, -0.25, 0]}
      />
      <mesh
        geometry={nodes.Torus001.geometry}
        material={nodes.Torus001.material}
        position={[6.95, 8.35, 0.47]}
        rotation={[Math.PI, -1.32, Math.PI]}
      />
      <mesh
        geometry={nodes.Torus002.geometry}
        material={nodes.Torus002.material}
        position={[5.44, 5.22, 2.4]}
        rotation={[Math.PI, -1.32, Math.PI]}
      />
      <mesh
        geometry={nodes.Torus003.geometry}
        material={nodes.Torus003.material}
        position={[6.23, 12.61, 1.67]}
        rotation={[Math.PI, -1.32, Math.PI]}
      />
      <mesh
        geometry={nodes.Circle.geometry}
        material={materials.ropeMaterial}
        position={[5.98, 1.12, -1.95]}
        rotation={[0.04, -0.15, 1.58]}
        scale={3}
      />
      <group position={[-1.9, 4.25, 6.26]} rotation={[0, -0.42, 0]}>
        <mesh
          geometry={nodes.Cube029_1.geometry}
          material={nodes.Cube029_1.material}
        />
        <mesh
          geometry={nodes.Cube029_2.geometry}
          material={nodes.Cube029_2.material}
        />
        <mesh
          geometry={nodes.Cube029_3.geometry}
          material={materials.whiteCubeMaterial}
        />
        <mesh
          geometry={nodes.Cube029_4.geometry}
          material={nodes.Cube029_4.material}
        />
        <mesh
          geometry={nodes.Cube029_5.geometry}
          material={materials.greenCubeMaterial}
        />
        <mesh
          geometry={nodes.Cube029_6.geometry}
          material={materials.yellCubeMaterial}
        />
      </group>
      <mesh
        geometry={nodes.Cube033.geometry}
        material={nodes.Cube033.material}
        position={[-8.85, 1.48, -6.89]}
        rotation={[1.57, 0, 0.25]}
      />
      <group
        position={[-8.66, 1.85, -6.16]}
        rotation={[-Math.PI, 0.67, -Math.PI]}
      >
        <mesh
          geometry={nodes.Cylinder006_1.geometry}
          material={nodes.Cylinder006_1.material}
        />
        <mesh
          geometry={nodes.Cylinder006_2.geometry}
          material={nodes.Cylinder006_2.material}
        />
        <mesh
          geometry={nodes.Cylinder006_3.geometry}
          material={nodes.Cylinder006_3.material}
        />
      </group>
      <mesh
        geometry={nodes.Cube029.geometry}
        material={nodes.Cube029.material}
        position={[-8.66, 1.53, -6.16]}
        rotation={[-Math.PI, 0.67, -Math.PI]}
      />
      <mesh
        geometry={nodes.Cube030.geometry}
        material={nodes.Cube030.material}
        position={[-8.5, 1.65, -6.04]}
        rotation={[-Math.PI, 0.67, -Math.PI]}
      />
      <mesh
        geometry={nodes.Cube031.geometry}
        material={nodes.Cube031.material}
        position={[-8.81, 1.65, -6.29]}
        rotation={[2.9, -0.74, 2.67]}
      />
      <mesh
        geometry={nodes.Cube032.geometry}
        material={nodes.Cube032.material}
        position={[-8.59, 1.65, -6.37]}
        rotation={[2.9, -0.74, 2.67]}
      />
      <mesh
        geometry={nodes.Cube034.geometry}
        material={nodes.Cube034.material}
        position={[-8.46, 1.93, -6.22]}
        rotation={[2.9, -0.74, 2.67]}
      />
      <mesh
        geometry={nodes.Cube035.geometry}
        material={nodes.Cube035.material}
        position={[-8.62, 1.93, -6.08]}
        rotation={[2.9, -0.74, 2.67]}
      />
      <mesh
        geometry={nodes.Cube036.geometry}
        material={nodes.Cube036.material}
        position={[-8.79, 2.14, -6.06]}
        rotation={[2.9, -0.74, 2.67]}
      />
      <mesh
        geometry={nodes.Cube037.geometry}
        material={nodes.Cube037.material}
        position={[-8.73, 2.14, -6.33]}
        rotation={[2.9, -0.74, 2.67]}
      />
      <mesh
        geometry={nodes.Cube038.geometry}
        material={nodes.Cube038.material}
        position={[-8.48, 2.22, -6.13]}
        rotation={[2.9, -0.74, 2.67]}
      />
      <mesh
        geometry={nodes.Cube039.geometry}
        material={nodes.Cube039.material}
        position={[-8.32, 2.38, -6]}
        rotation={[2.9, -0.74, 2.67]}
      />
      <mesh
        geometry={nodes.Cube040.geometry}
        material={nodes.Cube040.material}
        position={[-8.36, 2.26, -5.83]}
        rotation={[2.9, -0.74, 2.67]}
      />
      <mesh
        geometry={nodes.Cube041.geometry}
        material={nodes.Cube041.material}
        position={[-8.23, 2.1, -5.98]}
        rotation={[2.9, -0.74, 2.67]}
      />
      <group
        position={[6.55, 9.88, -4.76]}
        rotation={[-Math.PI, 0.25, Math.PI / 2]}
      >
        <mesh
          geometry={nodes.Cube016_1.geometry}
          material={nodes.Cube016_1.material}
        />
        <mesh
          geometry={nodes.Cube016_2.geometry}
          material={nodes.Cube016_2.material}
        />
      </group>
      <group
        position={[6.22, 9.92, -4.89]}
        rotation={[-Math.PI, 0.25, Math.PI / 2]}
      >
        <mesh
          geometry={nodes.Cube020_1.geometry}
          material={nodes.Cube020_1.material}
        />
        <mesh
          geometry={nodes.Cube020_2.geometry}
          material={nodes.Cube020_2.material}
        />
      </group>
      <group
        position={[5.83, 9.88, -4.78]}
        rotation={[-Math.PI, 0.25, Math.PI / 2]}
      >
        <mesh
          geometry={nodes.Cube021_1.geometry}
          material={nodes.Cube021_1.material}
        />
        <mesh
          geometry={nodes.Cube021_2.geometry}
          material={nodes.Cube021_2.material}
        />
      </group>
      <group
        position={[5.52, 9.86, -5.04]}
        rotation={[-Math.PI, 0.25, Math.PI / 2]}
      >
        <mesh
          geometry={nodes.Cube023_1.geometry}
          material={nodes.Cube023_1.material}
        />
        <mesh
          geometry={nodes.Cube023_2.geometry}
          material={materials["Material.005"]}
        />
      </group>
      <group position={[4.78, 10, -5.21]} rotation={[-Math.PI, 0.25, 1.96]}>
        <mesh
          geometry={nodes.Cube024_1.geometry}
          material={nodes.Cube024_1.material}
        />
        <mesh
          geometry={nodes.Cube024_2.geometry}
          material={materials.bookMaterial}
        />
      </group>
      <group position={[4.39, 9.42, -5.75]} rotation={[Math.PI, -1.32, 0]}>
        <mesh
          geometry={nodes.Cube026_1.geometry}
          material={nodes.Cube026_1.material}
        />
        <mesh
          geometry={nodes.Cube026_2.geometry}
          material={nodes.Cube026_2.material}
        />
      </group>
      <group position={[4.43, 9.81, -5.58]} rotation={[Math.PI, -1.02, 0]}>
        <mesh
          geometry={nodes.Cube027_1.geometry}
          material={nodes.Cube027_1.material}
        />
        <mesh
          geometry={nodes.Cube027_2.geometry}
          material={materials["Material.006"]}
        />
      </group>
      <mesh
        geometry={nodes.Plane004.geometry}
        material={nodes.Plane004.material}
        position={[-4.27, 0.87, -8.75]}
        rotation={[1.77, 0.05, 0.24]}
      />
      <mesh
        geometry={nodes.Cube050.geometry}
        material={nodes.Cube050.material}
        position={[-6.79, 7.51, -7.94]}
        rotation={[-1.37, -0.05, -0.24]}
      />
      <mesh
        geometry={nodes.Cube051.geometry}
        material={nodes.Cube051.material}
        position={[-6.58, 9.3, -7.54]}
        rotation={[-1.25, 0.29, -0.34]}
      />
      <mesh
        geometry={nodes.Cube052.geometry}
        material={nodes.Cube052.material}
        position={[-3.84, 7.51, -7.2]}
        rotation={[-1.37, -0.05, -0.24]}
      />
      <mesh
        geometry={nodes.Cube055.geometry}
        material={nodes.Cube055.material}
        position={[5.21, 1.68, -5.09]}
        rotation={[-3.14, -0.44, -1.57]}
      />
      <mesh
        geometry={nodes.Cube056.geometry}
        material={nodes.Cube056.material}
        position={[-6.71, 11.99, -7]}
        rotation={[-1.56, -0.63, -0.31]}
      />
      <mesh
        geometry={nodes.Cube053.geometry}
        material={nodes.Cube053.material}
        position={[-5.86, 6.61, -7.9]}
        rotation={[-2.88, 0.28, 2.16]}
      />
      <mesh
        geometry={nodes.Cube054.geometry}
        material={nodes.Cube054.material}
        position={[-0.69, 3.64, -7.26]}
        rotation={[-1.38, -0.38, -0.22]}
      />
      <mesh
        geometry={nodes.Cube057.geometry}
        material={nodes.Cube057.material}
        position={[-5.82, 5.72, -8.08]}
        rotation={[-2.88, 0.28, 2.16]}
      />
      <mesh
        geometry={nodes.Cube058.geometry}
        material={nodes.Cube058.material}
        position={[-6.86, 3.04, -8.92]}
        rotation={[-2.96, 0.3, -2.68]}
      />
      <mesh
        geometry={nodes.Cube059.geometry}
        material={nodes.Cube059.material}
        position={[-2.91, 9.53, -4.64]}
        rotation={[1.9, -0.44, 0.27]}
      />
      <mesh
        geometry={nodes.Cube060.geometry}
        material={nodes.Cube060.material}
        position={[-1.83, 1.86, -6.46]}
        rotation={[1.9, -0.44, 0.27]}
      />
      <mesh
        geometry={nodes.Cube061.geometry}
        material={nodes.Cube061.material}
        position={[-6.95, 3.96, -7.33]}
        rotation={[-1.6, -0.77, 2.8]}
      />
      <mesh
        geometry={nodes.Cube062.geometry}
        material={nodes.Cube062.material}
        position={[-3.62, 3.04, -8.1]}
        rotation={[-1.37, -0.05, -0.24]}
      />
      <mesh
        geometry={nodes.Cube063.geometry}
        material={nodes.Cube063.material}
        position={[-2.35, 11.21, -5.61]}
        rotation={[2.84, -0.14, -2.94]}
      />
      <mesh
        geometry={nodes.Cube064.geometry}
        material={nodes.Cube064.material}
        position={[-2.71, 9.26, -5.45]}
        rotation={[-0.71, 0.06, -0.34]}
      />
      <mesh
        geometry={nodes.Cube065.geometry}
        material={nodes.Cube065.material}
        position={[-1.41, 6.32, -6.87]}
        rotation={[-1.63, -0.91, -0.44]}
      />
      <mesh
        geometry={nodes.Cube066.geometry}
        material={nodes.Cube066.material}
        position={[-6.17, 0.95, -9.19]}
        rotation={[-2.96, 0.3, -2.68]}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={nodes.Cylinder004.material}
        position={[-3.33, 10.11, -6.1]}
        rotation={[3.03, -0.75, 1.64]}
      />
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={nodes.Cylinder005.material}
        position={[-3.06, 5.49, -7.82]}
        rotation={[-3.14, -1.32, 1.37]}
        scale={[1.41, 1, 1.3]}
      />
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={nodes.Cylinder006.material}
        position={[-5.27, 8.48, -7.74]}
        rotation={[-1.13, 0.6, 2.54]}
      />
      <mesh
        geometry={nodes.Cube067.geometry}
        material={nodes.Cube067.material}
        position={[-0.62, 8.1, -6.26]}
        rotation={[-1.37, -0.05, -0.24]}
      />
      <mesh
        geometry={nodes.Cube068.geometry}
        material={nodes.Cube068.material}
        position={[-1.64, 4.82, -7.22]}
        rotation={[-1.37, -0.05, -0.24]}
      />
      <mesh
        geometry={nodes.Cylinder007.geometry}
        material={nodes.Cylinder007.material}
        position={[-0.5, 1, -8.01]}
        rotation={[-3.14, -1.32, 1.37]}
      />
      <mesh
        geometry={nodes.Cube069.geometry}
        material={nodes.Cube069.material}
        position={[-5.23, 11.68, -6.66]}
        rotation={[-1.37, -0.05, -0.24]}
      />
      <mesh
        geometry={nodes.Cube070.geometry}
        material={nodes.Cube070.material}
        position={[-0.82, 11.98, -5.48]}
        rotation={[-1.37, -0.05, -0.24]}
      />
      <mesh
        geometry={nodes.Circle001.geometry}
        material={nodes.Circle001.material}
        position={[5.74, 0.2, -5.23]}
        rotation={[0, 0.45, 0]}
      />
      <mesh
        geometry={nodes.Cylinder008.geometry}
        material={nodes.Cylinder008.material}
        position={[6.09, 0.78, -5.4]}
        rotation={[0, 0.45, 0]}
      />
      <mesh
        geometry={nodes.Cube072.geometry}
        material={nodes.Cube072.material}
        position={[5.81, 5.29, -5.27]}
        rotation={[0.03, -1.12, -3.12]}
      />
      <mesh
        geometry={nodes.Cylinder010.geometry}
        material={nodes.Cylinder010.material}
        position={[5.48, 5.37, -5.3]}
        rotation={[-1.72, 0.3, -2.66]}
      />
      <mesh
        geometry={nodes.Cylinder012.geometry}
        material={nodes.Cylinder012.material}
        position={[5.54, 5.37, -5.33]}
        rotation={[-3.02, -0.46, 1.64]}
      />
      <group position={[3.12, 1.54, -5.41]} rotation={[0, 0.53, -1.66]}>
        <mesh
          geometry={nodes.Torus004_1.geometry}
          material={nodes.Torus004_1.material}
        />
        <mesh
          geometry={nodes.Torus004_2.geometry}
          material={nodes.Torus004_2.material}
        />
        <mesh
          geometry={nodes.Torus004_3.geometry}
          material={materials.meshMaterial}
        />
      </group>
      <group position={[4.93, 2.32, -4.79]} rotation={[0, 0.45, Math.PI / 2]}>
        <mesh
          geometry={nodes.Cube074_1.geometry}
          material={nodes.Cube074_1.material}
        />
        <mesh
          geometry={nodes.Cube074_2.geometry}
          material={nodes.Cube074_2.material}
        />
        <mesh
          geometry={nodes.Cube074_3.geometry}
          material={nodes.Cube074_3.material}
        />
      </group>
      <group position={[5.53, 5.78, -5.13]} rotation={[0, 0.45, Math.PI / 2]}>
        <mesh
          geometry={nodes.Cube075_1.geometry}
          material={nodes.Cube075_1.material}
        />
        <mesh
          geometry={nodes.Cube075_2.geometry}
          material={nodes.Cube075_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Cube075.geometry}
        material={nodes.Cube075.material}
        position={[5.7, 5.51, -4.86]}
        rotation={[0, 0.45, 1.49]}
      />
      <mesh
        geometry={nodes.Cylinder009.geometry}
        material={nodes.Cylinder009.material}
        position={[5.66, 2.75, -5.2]}
        rotation={[0, 0.45, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Cube076.geometry}
        material={nodes.Cube076.material}
        position={[5.64, 1.68, -5.19]}
        rotation={[0, 0.45, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Cube077.geometry}
        material={nodes.Cube077.material}
        position={[5.22, 1.68, -5.06]}
        rotation={[-3.14, -0.44, -1.57]}
      />
      <mesh
        geometry={nodes.Cube078.geometry}
        material={nodes.Cube078.material}
        position={[5.24, 1.68, -5.02]}
        rotation={[-3.14, -0.44, -1.57]}
      />
      <mesh
        geometry={nodes.Cube079.geometry}
        material={nodes.Cube079.material}
        position={[5.26, 1.68, -4.98]}
        rotation={[-3.14, -0.44, -1.57]}
      />
      <mesh
        geometry={nodes.Cube080.geometry}
        material={nodes.Cube080.material}
        position={[5.28, 1.68, -4.94]}
        rotation={[-3.14, -0.44, -1.57]}
      />
      <mesh
        geometry={nodes.Cube081.geometry}
        material={nodes.Cube081.material}
        position={[5.3, 1.68, -4.91]}
        rotation={[-3.14, -0.44, -1.57]}
      />
      <mesh
        geometry={nodes.Cube082.geometry}
        material={nodes.Cube082.material}
        position={[5.21, 1.76, -5.09]}
        rotation={[-3.14, -0.44, -1.57]}
      />
      <mesh
        geometry={nodes.Cube083.geometry}
        material={nodes.Cube083.material}
        position={[5.22, 1.76, -5.06]}
        rotation={[-3.14, -0.44, -1.57]}
      />
      <mesh
        geometry={nodes.Cube084.geometry}
        material={nodes.Cube084.material}
        position={[5.24, 1.76, -5.02]}
        rotation={[-3.14, -0.44, -1.57]}
      />
      <mesh
        geometry={nodes.Cube085.geometry}
        material={nodes.Cube085.material}
        position={[5.26, 1.76, -4.98]}
        rotation={[-3.14, -0.44, -1.57]}
      />
      <mesh
        geometry={nodes.Cube086.geometry}
        material={nodes.Cube086.material}
        position={[5.28, 1.76, -4.94]}
        rotation={[-3.14, -0.44, -1.57]}
      />
      <mesh
        geometry={nodes.Cube087.geometry}
        material={nodes.Cube087.material}
        position={[3.94, 1.76, -5.84]}
        rotation={[-3.14, -0.69, -1.57]}
      />
      <mesh
        geometry={nodes.Cube088.geometry}
        material={nodes.Cube088.material}
        position={[5.31, 5.55, -4.92]}
        rotation={[1.54, -0.07, -2.03]}
      />
      <mesh
        geometry={nodes.Cube089.geometry}
        material={nodes.Cube089.material}
        position={[5.31, 5.69, -4.95]}
        rotation={[1.54, -0.07, -2.03]}
      />
      <mesh
        geometry={nodes.Cube090.geometry}
        material={nodes.Cube090.material}
        position={[5.3, 5.81, -4.99]}
        rotation={[1.54, -0.07, -2.03]}
      />
      <mesh
        geometry={nodes.Cube094.geometry}
        material={nodes.Cube094.material}
        position={[5.23, 5.55, -5.08]}
        rotation={[1.54, -0.07, -2.03]}
      />
      <mesh
        geometry={nodes.Cube095.geometry}
        material={nodes.Cube095.material}
        position={[5.26, 5.69, -5.06]}
        rotation={[1.54, -0.07, -2.03]}
      />
      <mesh
        geometry={nodes.Cube096.geometry}
        material={nodes.Cube096.material}
        position={[5.28, 5.81, -5.03]}
        rotation={[1.54, -0.07, -2.03]}
      />
      <mesh
        geometry={nodes.Cube091.geometry}
        material={nodes.Cube091.material}
        position={[5.66, 3.48, -5.2]}
        rotation={[0, 0.45, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Cube092.geometry}
        material={nodes.Cube092.material}
        position={[5.71, 5.65, -4.87]}
        rotation={[0, 0.45, 1.49]}
      />
      <mesh
        geometry={nodes.Cube093.geometry}
        material={nodes.Cube093.material}
        position={[5.71, 5.78, -4.88]}
        rotation={[0, 0.45, 1.49]}
      />
      <mesh
        geometry={nodes.Cube097.geometry}
        material={nodes.Cube097.material}
        position={[4.92, 5.56, -5.18]}
        rotation={[-Math.PI, -0.45, -1.48]}
      />
      <mesh
        geometry={nodes.Cube098.geometry}
        material={nodes.Cube098.material}
        position={[4.93, 5.7, -5.18]}
        rotation={[-Math.PI, -0.45, -1.48]}
      />
      <mesh
        geometry={nodes.Cube099.geometry}
        material={nodes.Cube099.material}
        position={[4.94, 5.82, -5.18]}
        rotation={[-Math.PI, -0.45, -1.48]}
      />
      <mesh
        geometry={nodes.Plane003.geometry}
        material={nodes.Plane003.material}
        position={[5.3, 5.31, -5.02]}
        rotation={[0, 0.45, Math.PI]}
      />
      <mesh
        geometry={nodes.Plane005.geometry}
        material={nodes.Plane005.material}
        position={[5.3, 5.21, -5.02]}
        rotation={[0, 0.45, Math.PI]}
      />
      <mesh
        geometry={nodes.Plane006.geometry}
        material={nodes.Plane006.material}
        position={[5.3, 5.1, -5.02]}
        rotation={[0, 0.45, Math.PI]}
      />
      <mesh
        geometry={nodes.Plane007.geometry}
        material={nodes.Plane007.material}
        position={[5.3, 4.99, -5.02]}
        rotation={[0, 0.45, Math.PI]}
      />
      <mesh
        geometry={nodes.Plane008.geometry}
        material={nodes.Plane008.material}
        position={[5.3, 4.89, -5.02]}
        rotation={[0, 0.45, Math.PI]}
      />
      <mesh
        geometry={nodes.Plane009.geometry}
        material={nodes.Plane009.material}
        position={[5.3, 4.78, -5.02]}
        rotation={[0, 0.45, Math.PI]}
      />
      <mesh
        geometry={nodes.Plane010.geometry}
        material={nodes.Plane010.material}
        position={[5.3, 4.67, -5.02]}
        rotation={[0, 0.45, Math.PI]}
      />
      <mesh
        geometry={nodes.Plane011.geometry}
        material={nodes.Plane011.material}
        position={[5.3, 4.56, -5.02]}
        rotation={[0, 0.45, Math.PI]}
      />
      <mesh
        geometry={nodes.Plane012.geometry}
        material={nodes.Plane012.material}
        position={[5.3, 4.45, -5.02]}
        rotation={[0, 0.45, Math.PI]}
      />
      <mesh
        geometry={nodes.Plane013.geometry}
        material={nodes.Plane013.material}
        position={[5.3, 4.33, -5.02]}
        rotation={[0, 0.45, Math.PI]}
      />
      <mesh
        geometry={nodes.Plane014.geometry}
        material={nodes.Plane014.material}
        position={[5.3, 4.22, -5.02]}
        rotation={[0, 0.45, Math.PI]}
      />
      <mesh
        geometry={nodes.Plane015.geometry}
        material={nodes.Plane015.material}
        position={[5.3, 4.11, -5.02]}
        rotation={[0, 0.45, Math.PI]}
      />
      <mesh
        geometry={nodes.Plane016.geometry}
        material={nodes.Plane016.material}
        position={[5.3, 4.01, -5.02]}
        rotation={[0, 0.45, Math.PI]}
      />
      <mesh
        geometry={nodes.Plane017.geometry}
        material={nodes.Plane017.material}
        position={[5.3, 3.9, -5.02]}
        rotation={[0, 0.45, Math.PI]}
      />
      <mesh
        geometry={nodes.Plane018.geometry}
        material={nodes.Plane018.material}
        position={[5.3, 3.8, -5.02]}
        rotation={[0, 0.45, Math.PI]}
      />
      <mesh
        geometry={nodes.Plane019.geometry}
        material={nodes.Plane019.material}
        position={[5.3, 3.7, -5.02]}
        rotation={[0, 0.45, Math.PI]}
      />
      <mesh
        geometry={nodes.Plane020.geometry}
        material={nodes.Plane020.material}
        position={[5.3, 3.11, -5.02]}
        rotation={[0, 0.45, Math.PI]}
      />
      <mesh
        geometry={nodes.Plane021.geometry}
        material={nodes.Plane021.material}
        position={[5.3, 3.16, -5.02]}
        rotation={[0, 0.45, Math.PI]}
      />
      <mesh
        geometry={nodes.Plane022.geometry}
        material={nodes.Plane022.material}
        position={[5.3, 3.2, -5.02]}
        rotation={[0, 0.45, Math.PI]}
      />
      <mesh
        geometry={nodes.Plane023.geometry}
        material={nodes.Plane023.material}
        position={[5.3, 3.24, -5.02]}
        rotation={[0, 0.45, Math.PI]}
      />
      <mesh
        geometry={nodes.Plane024.geometry}
        material={nodes.Plane024.material}
        position={[5.3, 3.62, -5.02]}
        rotation={[0, 0.45, Math.PI]}
      />
      <mesh
        geometry={nodes.Plane025.geometry}
        material={nodes.Plane025.material}
        position={[5.3, 3.55, -5.02]}
        rotation={[0, 0.45, Math.PI]}
      />
      <mesh
        geometry={nodes.Plane026.geometry}
        material={nodes.Plane026.material}
        position={[5.3, 3.48, -5.02]}
        rotation={[0, 0.45, Math.PI]}
      />
      <mesh
        geometry={nodes.Plane027.geometry}
        material={nodes.Plane027.material}
        position={[5.3, 3.41, -5.02]}
        rotation={[0, 0.45, Math.PI]}
      />
      <mesh
        geometry={nodes.Plane028.geometry}
        material={nodes.Plane028.material}
        position={[5.3, 3.35, -5.02]}
        rotation={[0, 0.45, Math.PI]}
      />
      <mesh
        geometry={nodes.Plane029.geometry}
        material={nodes.Plane029.material}
        position={[5.3, 3.29, -5.02]}
        rotation={[0, 0.45, Math.PI]}
      />
      <mesh
        geometry={nodes.Cylinder011.geometry}
        material={nodes.Cylinder011.material}
        position={[5.66, 5.37, -5.05]}
        rotation={[-3.02, -0.46, 1.64]}
      />
      <group
        position={[5.73, 6.97, -6.35]}
        rotation={[-Math.PI, 0.53, -Math.PI]}
      >
        <mesh
          geometry={nodes.Cylinder020_1.geometry}
          material={nodes.Cylinder020_1.material}
        />
        <mesh
          geometry={nodes.Cylinder020_2.geometry}
          material={nodes.Cylinder020_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Cylinder014.geometry}
        material={nodes.Cylinder014.material}
        position={[3.89, 6.64, -5.94]}
        rotation={[-Math.PI, 0.53, -Math.PI]}
      />
      <mesh
        geometry={nodes.Cylinder015.geometry}
        material={nodes.Cylinder015.material}
        position={[4.68, 6.64, -7.27]}
        rotation={[-Math.PI, 0.53, -Math.PI]}
      />
      <mesh
        geometry={nodes.Cylinder016.geometry}
        material={nodes.Cylinder016.material}
        position={[6.02, 6.64, -6.49]}
        rotation={[-Math.PI, 0.53, -Math.PI]}
      />
      <group
        position={[5.24, 6.84, -5.14]}
        rotation={[-Math.PI, 0.53, -Math.PI]}
      >
        <mesh
          geometry={nodes.Cube110.geometry}
          material={nodes.Cube110.material}
        />
        <mesh
          geometry={nodes.Cube110_1.geometry}
          material={nodes.Cube110_1.material}
        />
        <mesh
          geometry={nodes.Cube110_2.geometry}
          material={nodes.Cube110_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Cylinder017.geometry}
        material={nodes.Cylinder017.material}
        position={[5.28, 7.06, -6.05]}
        rotation={[-Math.PI, 0.53, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Cylinder018.geometry}
        material={nodes.Cylinder018.material}
        position={[6.09, 7.06, -5.58]}
        rotation={[-Math.PI, 0.53, Math.PI / 2]}
      />
      <group position={[5.78, 7.77, -6.06]} rotation={[-1.63, 0.03, 2.61]}>
        <mesh
          geometry={nodes.Cube111.geometry}
          material={nodes.Cube111.material}
        />
        <mesh
          geometry={nodes.Cube111_1.geometry}
          material={nodes.Cube111_1.material}
        />
      </group>
      <group
        position={[5.67, 6.97, -5.95]}
        rotation={[-Math.PI, 0.53, -Math.PI]}
      >
        <mesh
          geometry={nodes.Cylinder026_1.geometry}
          material={nodes.Cylinder026_1.material}
        />
        <mesh
          geometry={nodes.Cylinder026_2.geometry}
          material={nodes.Cylinder026_2.material}
        />
      </group>
      <group
        position={[5.57, 6.97, -5.77]}
        rotation={[-Math.PI, 0.53, -Math.PI]}
      >
        <mesh
          geometry={nodes.Cylinder027_1.geometry}
          material={nodes.Cylinder027_1.material}
        />
        <mesh
          geometry={nodes.Cylinder027_2.geometry}
          material={nodes.Cylinder027_2.material}
        />
      </group>
      <mesh
        geometry={nodes.Cylinder021.geometry}
        material={nodes.Cylinder021.material}
        position={[5.1, 7.03, -5.1]}
        rotation={[-Math.PI, 0.53, -Math.PI]}
      />
      <mesh
        geometry={nodes.Cylinder022.geometry}
        material={nodes.Cylinder022.material}
        position={[5.09, 7.04, -5.09]}
        rotation={[-Math.PI, 0.53, -Math.PI]}
      />
      <mesh
        geometry={nodes.Circle019.geometry}
        material={nodes.Circle019.material}
        position={[5.09, 7.04, -5.09]}
        rotation={[-Math.PI, 0.53, -Math.PI]}
      />
      <mesh
        geometry={nodes.Cube102.geometry}
        material={nodes.Cube102.material}
        position={[5.08, 6.96, -5.83]}
        rotation={[Math.PI, -0.01, Math.PI]}
      />
      <mesh
        geometry={nodes.Cylinder023.geometry}
        material={nodes.Cylinder023.material}
        position={[5.23, 6.64, -5.15]}
        rotation={[-Math.PI, 0.53, -Math.PI]}
      />
      <mesh
        geometry={nodes.Cylinder024.geometry}
        material={nodes.Cylinder024.material}
        position={[4.94, 7, -6.35]}
        rotation={[-Math.PI, 0.53, -Math.PI]}
      />
      <mesh
        geometry={nodes.Cylinder025.geometry}
        material={nodes.Cylinder025.material}
        position={[5.07, 7.06, -5.82]}
        rotation={[Math.PI, -0.99, Math.PI / 2]}
      />
      <mesh
        geometry={nodes.Cylinder026.geometry}
        material={nodes.Cylinder026.material}
        position={[4.77, 7.06, -5.3]}
        rotation={[-Math.PI, 0.53, -Math.PI]}
      />
      <mesh
        geometry={nodes.Plane030.geometry}
        material={nodes.Plane030.material}
        position={[3.02, 6.67, -5.77]}
        rotation={[0, -0.36, 0]}
      />
      <mesh
        geometry={nodes.Plane031.geometry}
        material={nodes.Plane031.material}
        position={[1.84, 7.59, -6.07]}
        rotation={[0, -0.25, 1.68]}
      />
      <mesh
        geometry={nodes.Plane032.geometry}
        material={nodes.Plane032.material}
        position={[3.14, 6.73, -5.86]}
        rotation={[0, -0.08, 0]}
      />
      <mesh
        geometry={nodes.Plane033.geometry}
        material={nodes.Plane033.material}
        position={[3.02, 6.76, -5.77]}
        rotation={[0, -0.32, 0]}
      />
      <mesh
        geometry={nodes.Plane034.geometry}
        material={nodes.Plane034.material}
        position={[3.2, 6.79, -5.97]}
        rotation={[0, 1, 0]}
      />
      <mesh
        geometry={nodes.Plane035.geometry}
        material={nodes.Plane035.material}
        position={[3.14, 6.89, -5.86]}
        rotation={[0, -0.21, 0]}
      />
      <mesh
        geometry={nodes.Circle002.geometry}
        material={nodes.Circle002.material}
        position={[3.03, 6.92, -5.61]}
        rotation={[-Math.PI, 0.53, -Math.PI]}
      />
      <mesh
        geometry={nodes.Cylinder027.geometry}
        material={nodes.Cylinder027.material}
        position={[2.75, 6.14, 8.26]}
        rotation={[-Math.PI, 1.41, -Math.PI]}
      />
      <mesh
        geometry={nodes.Sphere.geometry}
        material={nodes.Sphere.material}
        position={[2.75, 7, 8.26]}
        rotation={[-Math.PI, 1.41, -Math.PI]}
      />
      <mesh
        geometry={nodes.Cylinder028.geometry}
        material={nodes.Cylinder028.material}
        position={[2.75, 0.77, 8.26]}
        rotation={[-Math.PI, 1.41, -Math.PI]}
      />
      <mesh
        geometry={nodes.Torus005.geometry}
        material={materials.dirtMaterial}
        position={[2.75, 3.3, 8.26]}
        rotation={[-Math.PI, 1.41, -Math.PI]}
      />
      <mesh
        geometry={nodes.Cylinder030.geometry}
        material={nodes.Cylinder030.material}
        position={[2.84, 5.25, 8.79]}
        rotation={[-Math.PI, 1.41, -2.16]}
      />
      <mesh
        geometry={nodes.Cylinder031.geometry}
        material={nodes.Cylinder031.material}
        position={[2.66, 6.32, 7.73]}
        rotation={[2.47, 1.14, 2.8]}
      />
      <mesh
        geometry={nodes.Cylinder032.geometry}
        material={nodes.Cylinder032.material}
        position={[2.13, 4.18, 7.82]}
        rotation={[-Math.PI, 0.58, 2.03]}
      />
      <group
        position={[-0.18, 4.34, 6.26]}
        rotation={[-Math.PI, -0.22, -Math.PI]}
      >
        <mesh
          geometry={nodes.Cube114.geometry}
          material={nodes.Cube114.material}
        />
        <mesh
          geometry={nodes.Cube114_1.geometry}
          material={nodes.Cube114_1.material}
        />
      </group>
      <group position={[-8.51, 1.04, 2.84]} rotation={[0, -0.25, 0]}>
        <mesh
          geometry={nodes.Icosphere002.geometry}
          material={nodes.Icosphere002.material}
        />
        <mesh
          geometry={nodes.Icosphere002_1.geometry}
          material={nodes.Icosphere002_1.material}
        />
      </group>
      <mesh
        geometry={nodes.Cube071.geometry}
        material={nodes.Cube071.material}
        position={[-6, 0.3, -6]}
        rotation={[0, -0.26, 0]}
        scale={[1.9, 1, -2.86]}
      />
      <mesh
        geometry={nodes.Cube027.geometry}
        material={nodes.Cube027.material}
        position={[-2.14, 0.3, -5.05]}
        rotation={[0, -0.26, 0]}
        scale={[1.9, 1, -2.86]}
      />
    </group>
  );
}

useGLTF.preload("/myroom.glb");
